# Generated by Django 6.1.1 on 2026-09-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feels_like', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.PositiveSmallIntegerField()),
                ('pressure', models.PositiveIntegerField()),
                ('weather', models.CharField(max_length=100)),
                ('collected_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
    ]
